stages:
  - test
  - release
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PROD_ZIEL: /var/www/kodirepo.elaon.de/web/


test:
  stage: test
  image: alpine:latest
  before_script:
    - apk add --no-cache git libxml2-utils
  script:
    - echo "Linting reposource/repository.elaonde/addon.xml"
    - xmllint -noout reposource/repository.elaonde/addon.xml

    - echo "Linting reposource/repository.elaondetesting/addon.xml"
    - xmllint -noout reposource/repository.elaondetesting/addon.xml

    - echo "Linting webroot/repo/addons.xml"
    - xmllint -noout webroot/repo/addons.xml
    
    - echo "Linting webroot/repo-testing/addons.xml"
    - xmllint -noout webroot/repo-testing/addons.xml


process-changed-zip:
  stage: release
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_AUTHOR != "Alex. F. (CI)"'
      when: on_success
    - when: never
  image: alpine:latest
  script:
    - apk add --no-cache git python3 py3-pip bash openssh libxml2-utils
    - eval $(ssh-agent -s)
    - echo "$SSH_DEPLOY_KEY" | base64 -d | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    
    - git fetch origin main
    - git checkout -B main origin/main
    - ./tools/update_repository.sh
    - git branch
    - git config --global user.email "ci@git.elaon.de"
    - git config --global user.name "Alex. F. (CI)"
    - git add .
    - git status
    - git commit -m "Update repos"
    - git remote set-url origin https://$GITHUB_TOKEN@github.com/elaon-de/repository.elaonde.git
    - git push origin main
    - git remote set-url origin git@git.elaon.de:alex/repository.elaonde.git
    - git push origin main

deploy2prod:
  stage: deploy
  environment: production
  script:
    - "echo Vorherige Dateien:"
    - ls -la $PROD_ZIEL
    - echo Lösche alte Dateien am '${PROD_ZIEL}' ...
    - rm -r ${PROD_ZIEL}* || echo "Keine Dateien vorhanden"
    - echo Deploye Webseite nach '${PROD_ZIEL}' ...
    - cp -r * $PROD_ZIEL
    - echo "Passe Rechte auf (www-data) an..."
    - "chown -R 33: $PROD_ZIEL"
    - "echo Endstand am Ziel:"
    - ls -la $PROD_ZIEL
  only:
    - main
  tags:
    - kodirepo
