stages:
  - test
  - release



test:
  stage: test
  image: alpine:latest
  before_script:
    - apk add --no-cache git git-lfs zip grep sed coreutils rsync libxml2-utils
  script:
    - echo "Linting reposource/repository.elaonde/addon.xml"
    - xmllint -noout reposource/repository.elaonde/addon.xml

    - echo "Linting reposource/repository.elaondetesting/addon.xml"
    - xmllint -noout reposource/repository.elaondetesting/addon.xml

    # - echo "Linting webroot/repo/addons.xml"
    # - xmllint -noout webroot/repo/addons.xml
    
    # - echo "Linting webroot/repo-testing/addons.xml"
    # - xmllint -noout webroot/repo-testing/addons.xml


process-changed-zip:
  stage: release
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_AUTHOR != "Alex. F. (CI)"'
      when: on_success
    - when: never
  image: alpine:latest
  script:
    - apk add --no-cache git python3 py3-pip bash
    - git fetch origin main
    - git checkout -B main origin/main
    - ./tools/update_repository.sh
    #- git diff
    - git branch
    - git config --global user.email "ci@git.elaon.de"
    - git config --global user.name "Alex. F. (CI)"
    - git add .
    - git status
    - git commit -m "Update repos"
    - git remote set-url origin https://$GITHUB_TOKEN@github.com/elaon-de/repository.elaonde.git
    - git push origin main
    - git remote set-url origin https://gitlab-ci-token:$CI_JOB_TOKEN@git.elaon.de/alex/repository.elaonde.git
    - git push origin main